export { PrimerPaso } from './PrimerPaso';
export { SegundoPaso } from './SegundoPaso';
export { TercerPaso } from './TercerPaso';
export { CuartoPaso } from './CuartoPaso';
export { QuintoPaso } from './QuintoPaso';
export { SextoPaso } from './SextoPaso';
export { SeptimoPaso } from './SeptimoPaso';
export { OctavoPaso } from './OctavoPaso';
export { Final } from './Final';
