export const defaultData = [
  {
    TipoAuditoria: 'Directa',
    NoAuditoria: 1,
    ProgramaAuditado: 'lorem',
    EjercicioAuditado: 'lorem2',
    DependenciaEjecutora: 'lorem3',
    Entidad: 'lorem',
    status: 'Planeacion',
  },
  {
    TipoAuditoria: 'Conjuntas',
    NoAuditoria: 1,
    ProgramaAuditado: 'lorem',
    EjercicioAuditado: 'lorem2',
    DependenciaEjecutora: 'lorem3',
    Entidad: 'lorem',
    status: 'Conclusión',
  },
  {
    TipoAuditoria: 'Revisiones',
    NoAuditoria: 1,
    ProgramaAuditado: 'lorem',
    EjercicioAuditado: 'lorem2',
    DependenciaEjecutora: 'lorem3',
    Entidad: 'lorem',
    status: 'Ejecucion',
  },
  {
    TipoAuditoria: 'Evaluaciones',
    NoAuditoria: 1,
    ProgramaAuditado: 'lorem',
    EjercicioAuditado: 'lorem2',
    DependenciaEjecutora: 'lorem3',
    Entidad: 'lorem',
    status: 'Seguimiento',
  },
  {
    TipoAuditoria: 'Evaluaciones',
    NoAuditoria: 1,
    ProgramaAuditado: 'lorem',
    EjercicioAuditado: 'lorem2',
    DependenciaEjecutora: 'lorem3',
    Entidad: 'lorem',
    status: 'Informe',
  },
];
